[build-system]
requires = [
    "setuptools>=42",
    "setuptools_scm[toml]>=3.4",
    "wheel"
]

[tool.setuptools_scm]
write_to = 'src/soc_roman_tools/version.py'

[flake8]
max-line-length = 88
ignore = F841
